# Generated by Django 2.0.1 on 2018-02-12 22:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accidents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('injured', models.IntegerField()),
                ('death', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=2)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(max_length=10)),
                ('address', models.TextField(max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('timestamp', models.TextField(max_length=8)),
                ('tax', models.FloatField()),
                ('discount', models.BooleanField()),
                ('points', models.IntegerField()),
                ('informer', models.TextField(max_length=50)),
                ('fact', models.TextField(max_length=500)),
                ('speed_limit', models.FloatField(null=True)),
                ('speed_reg', models.FloatField(null=True)),
                ('geocoder_info', models.TextField(max_length=1000)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='MultasRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.TextField()),
                ('lugar', models.TextField()),
                ('mes', models.TextField()),
                ('anio', models.TextField()),
                ('hora', models.TextField()),
                ('imp_bol', models.TextField()),
                ('descuento', models.TextField()),
                ('puntos', models.TextField()),
                ('denunciante', models.TextField()),
                ('hecho_bol', models.TextField()),
                ('vel_limite', models.TextField()),
                ('vel_circula', models.TextField()),
                ('coordenada_x', models.TextField()),
                ('coordenada_y', models.TextField()),
                ('procesado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('code2', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=50)),
                ('district_name', models.CharField(max_length=50)),
                ('district_code', models.CharField(max_length=2)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='accidents',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='madrid.District'),
        ),
    ]
