# Generated by Django 2.0.1 on 2018-02-12 22:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madrid', '0003_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=25830),
        ),
        migrations.AlterField(
            model_name='fine',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=25830),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=25830),
        ),
    ]
